Fix "Run tests" CI step (#76)
* Fix test_trailing_endline adding a required new line at the of the file

* Fix value error for converting "memory": "xGB" as float

The `memory` field must be a float.
Also re-sync CSV files (US to FR).

* Fix ModuleNotFoundError: No module named 'matplotlib'

* Fix testdata for Google parser (AssertionError: Lists differ)

* Fix "AssertionError: Missing parser" for HP parser

ParsersTest requires that parser's name and parser's testdata directory use
the same name.

* Fix testdata for dell_laptop parser (AssertionError: Lists differ)

* Fix testdata for lenovo parser (AssertionError: Lists differ)

* Fix testdata for hp_workplace parser (AssertionError: Lists differ)

* Fix TypeError: float() on Google parser

The regex was failing with:

  TypeError: float() argument must be a string or a number, not
  'NoneType'

due to a missing group.